"""Modelo Vehiculo

Revision ID: 927105a9f875
Revises: bdd0585addbc
Create Date: 2024-06-25 20:04:50.787361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927105a9f875'
down_revision = 'bdd0585addbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
